[package]
name = "advent-of-code-2015"
version = "0.1.0"
edition = "2021"

[dependencies]
md5 = "0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "template"
path = "template/main.rs"

[[bin]]
name = "01"
path = "01/main.rs"

[[bin]]
name = "02"
path = "02/main.rs"

[[bin]]
name = "03"
path = "03/main.rs"

[[bin]]
name = "04"
path = "04/main.rs"

[[bin]]
name = "05"
path = "05/main.rs"

[[bin]]
name = "06"
path = "06/main.rs"

[[bin]]
name = "07"
path = "07/main.rs"
